export const team405Data = {
  name: "405 Found",
  domain: "Web",
  teamLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamCoLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamMembers: [
    {
      id: 1,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 2,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 3,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 4,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 5,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 6,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 7,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 8,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
  ],
};

export const flutterTeamData = {
  name: "Nougat",
  domain: "Flutter",
  teamLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamCoLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamMembers: [
    {
      id: 1,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 2,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 3,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 4,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
  ],
};

export const kotlinTeamData = {
  name: "Nougat",
  domain: "Kotlin",
  teamLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamCoLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamMembers: [
    {
      id: 1,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 2,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 3,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 4,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy engineering",
      linkedIn: "#",
    },
  ],
};

export const AiMlTeamData = {
  name: "Gray Interface",
  domain: "AI/ML",
  teamLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamCoLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamMembers: [
    {
      id: 1,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 2,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 3,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 4,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 5,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 6,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 7,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
  ],
};

export const blockchainTeamData = {
  name: "CipherSync",
  domain: "blockchain",
  teamLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamCoLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamMembers: [
    {
      id: 1,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 2,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 3,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 4,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
  ],
};

export const DSATeamData = {
  name: "SigSTP",
  domain: "DSA",
  teamLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamCoLead: {
    name: "Devendra Singh",
    image: "/leads/FlutterLead.png",
    department: "Computer Science Department",
    domain: "Development",
    headLine: "Any one line statement representing sir's view",
    linkedIn: "#",
  },
  teamMembers: [
    {
      id: 1,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 2,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 3,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
    {
      id: 4,
      name: "dummy team member",
      image: "/leads/FlutterLead.png",
      department: "dummy Engineering",
      linkedIn: "#",
    },
  ],
};
